# SonarQube project configuration — auth-service
# Self-hosted SonarQube (no sonar.organization needed)
sonar.projectKey=shopnova-auth-service
sonar.projectName=ShopNova Auth Service
sonar.projectVersion=1.0

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.test.js,**/*.spec.js

# Node.js / JavaScript
sonar.javascript.lcov.reportPaths=coverage/lcov.info
